### ISSUE TITLE
Demo Video

### ISSUE THREAD

**Issue by impulsecorp** [abhishekkr/lyrical-video-generator#1]
It would be great if you could upload one of the videos you made with this, or a link to one.

**Comment by abhishekkr** [comment]
> It would be great if you could upload one of the videos you made with this, or a link to one.

@impulsecorp hi, I somehow missed notification for this.

The following playlist has all the videos created using it..

https://youtube.com/playlist?list=PLHyBm8d4YRSkXMxo43CPrBp4Un2_sFosg

Although, currently Audio speed had to be tweaked separately to match Video length... and merger for these were done explicitly using FFMPEG (some with OpenShot).

I'll be opening an issue as a reminder to work on those aspects.
